server:
  port: 19992
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: lettuce
    password: redisPwd
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
cache:
  default-duration: 300
  type: redis
zblog:
  deploy-type: single
  is-local-ip-parsing: true