server:
  port: 19993
spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-2zesvm06o324og1k3bo.mysql.rds.aliyuncs.com:3306/zblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: ENC(hisvsQ4rjMY755ISBof8XuElj9jw2dmG)
      password: ENC(PHOwc8TXSX9upQ0FgWJ7KbyIn26EfI19)
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: lettuce
    password: redisPwd
cache:
  default-duration: 300
  type: redis
zblog:
  deploy-type: single
  is-local-ip-parsing: false