spring:
  profiles:
    active: alpha
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  freemarker:
    check-template-location: false
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-enums-package: com.github.stazxr.zblog.**.domain.enums
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
logging:
  file:
    path: /home/zblog/logs/zblog.log
swagger:
  config:
    enable: true
    title: zblog 官方文档
    description: 一个前后端分离的个人博客框架，代码直通车 👉 https://github.com/stazxr/zblog
    version: 4.0.0
    base-package: com.github.stazxr.zblog
    contact:
      name: SunTao
      url: https://www.suntaoblog.com
      email: 1027353579@qq.com
zblog:
  base-package: com.github.stazxr.zblog