spring:
  profiles:
    active: prod
swagger:
  config:
    enable: ${spring.web.resources.add-mappings}
    title: zblog 官方文档
    description: 一个前后端分离的个人博客框架，Git链接：https://github.com/stazxr/zblog
    version: 4.0.0
    base-package: com.github.stazxr.zblog
    contact:
      name: SunTao
      url: https://www.suntaoblog.com/
      email: stazxr@qq.com
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
  type-enums-package: com.github.stazxr.zblog.base.domain.enums
deploy:
  type: single
