server:
  port: 19993
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2zesvm06o324og1k3bo.mysql.rds.aliyuncs.com:3306/zblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ENC(hisvsQ4rjMY755ISBof8XuElj9jw2dmG)
    password: ENC(PHOwc8TXSX9upQ0FgWJ7KbyIn26EfI19)
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: lettuce
    password: redisPwd
jwt:
  cert-info:
    alias: zblog
    key-password: 123456
    cert-location: zblog.jks
  claims:
    issuer: https://www.suntaoblog.com
    subject: all
    duration: 1800
cache:
  default-duration: 300
  type: redis
zblog:
  deploy-type: single
  is-local-ip-parsing: false