server:
  port: 9999
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    add-properties: false
  redis:
    host: 127.0.0.1
    port: 6480
    client-type: lettuce
    password: redis@Pwd
jwt:
  cert-info:
    alias: zblog
    key-password: 123456
    cert-location: zblog.jks
  claims:
    issuer: https://www.suntaoblog.com
    subject: all
    duration: 60
  cache-type: ehcache