spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: xxxxxx
    username: xxxxxx
    password: xxxxxx
    type: com.alibaba.druid.pool.DruidDataSource
jwt:
  config:
    enabled: true
    key-location: zblog.jks
    key-alias: zblog
    key-pass: 123456
    iss: zblog.space
    sub: all
    access-exp-days: 3
    refresh-exp-days: 7