spring:
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.github.spring.security.mapper: debug
    org.springframework.security: debug
jwt:
  config:
    enabled: true
    key-location: zblog.jks
    key-alias: zblog
    key-pass: 123456
    iss: zblog.space
    sub: all
    access-exp-days: 1
    refresh-exp-days: 3