server:
  port: ${serverPort:31945}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2zesvm06o324og1k3bo.mysql.rds.aliyuncs.com:3306/zblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ENC(hisvsQ4rjMY755ISBof8XuElj9jw2dmG)
    password: ENC(PHOwc8TXSX9upQ0FgWJ7KbyIn26EfI19)
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: ENC(wEAkOysMms4sh54ilxS+TLLkIXxGGN7L)
    port: 6480
    client-type: lettuce
    password: ENC(yLNmRC4j7X2ucajRvSutQTSbnrwi9eoM)
jwt:
  cert-info:
    alias: suntaoblogcom
    key-password: ENC(kUfidmIYBnle2iOXS1MSqQvzU+VOhCXQ)
    cert-location: suntaoblogcom.jks
  claims:
    issuer: https://www.suntaoblog.com
    subject: all
    duration: 1800
cache:
  default-duration: 300
  type: redis
zblog:
  deploy-type: single
  is-local-ip-parsing: true
swagger:
  config:
    enable: false # 生产环境禁用 swagger