spring:
  profiles:
    active: alpha
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  freemarker:
    check-template-location: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.qq.com
    port: 587
    protocol: smtp
    username: stazxr@qq.com
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
logging:
  file:
    path: /home/zblog/logs/services
swagger:
  config:
    enable: true
    title: zblog 官方文档
    description: 一个前后端分离的个人博客框架，代码直通车 👉 https://github.com/stazxr/zblog
    version: 4.0.0
    base-package: com.github.stazxr.zblog
    contact:
      name: SunTao
      url: https://www.suntaoblog.com
      email: 1027353579@qq.com
jwt:
  access-token-duration: 1800
  refresh-token-duration: 43200
  allowed-renew-token: true
  refresh-min-duration: 600
  max-version: 10
  algorithm: RS256
  cert-info:
    alias: zblog
    key-password: 123456
    cert-location: zblog.jks
  claims:
    issuer: http://localhost:${server.port}
    subject: Login
zblog:
  base-package: com.github.stazxr.zblog
  file-base-url: http://localhost:${server.port}/file/
  file-upload-path: /home/zblog/file/local/upload/
  file-domain: /file/**
  file-upload-type: 1